### ISSUE TITLE
Everything broke.

### ISSUE THREAD

**Issue by Pronner** [RaphMar2021/SipaaOperatingSystem#2]
I'm getting errors about all the References imported, all of them have warnings and I cannot compile/build the Visual OS. I recommend you to publish a release so people can use it easily instead of needing to download the source code then somehow fix every broken thing in the code and in the project then run it.

Also for some reason in "Resources.resx" it imports Images from my computer and if they're not found it does not run and I get an error. I'm guessing when you added the images you chose to Locally Import it instead of adding it into the Resources Folder.

**Comment by Pronner** [comment]
I just realized I need to use VS2022 to use this, so I will try it out with VS2022. Although, I still recommend that you publish a release.

**Comment by Pronner** [comment]
It's already added there, but I've used VS 2019 so that might be the problem. Give me a few minutes.

**Comment by RaphMar2021** [comment]
Are you a good WIFI?

**Comment by Pronner** [comment]
Yeah I do, why?

**Comment by Pronner** [comment]
Okay so I just tested the source code, it's still broken. You should probably make a release of the exe otherwise no one can use it.

**Comment by RaphMar2021** [comment]
Okay, je vais l'a produire

**Comment by RaphMar2021** [comment]
Envoyer-moi une capture de Visual Studio

**Comment by Pronner** [comment]
I don't speak French sorry

**Comment by RaphMar2021** [comment]
Send me a Visual Studio capture. Sorry
